### ISSUE TITLE
websocket好像维持不了几秒钟就断了

### ISSUE THREAD

**Issue by AdamsLee** [opendilab/CleanS2S#25]
点击前端Speech to Speech Chat后没几秒就断了，后端日志如下：
INFO:__main__:Warming up ParaFormerSTTHandler
INFO:__main__:ParaFormerSTTHandler:  warmed up! time: 2.332 s
2024-12-22 19:48:59.969063120 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 12 Memcpy nodes are added to the graph main_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2024-12-22 19:48:59.971087376 [W:onnxruntime:, session_state.cc:1166 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-12-22 19:48:59.971110138 [W:onnxruntime:, session_state.cc:1168 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2024-12-22 19:49:00,265 WETEXT INFO found existing fst: /opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/tn/zh_tn_tagger.fst
INFO:wetext-zh_normalizer:found existing fst: /opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/tn/zh_tn_tagger.fst
2024-12-22 19:49:00,265 WETEXT INFO                     /opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/tn/zh_tn_verbalizer.fst
INFO:wetext-zh_normalizer:                    /opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/tn/zh_tn_verbalizer.fst
2024-12-22 19:49:00,265 WETEXT INFO skip building fst for zh_normalizer ...
INFO:wetext-zh_normalizer:skip building fst for zh_normalizer ...
2024-12-22 19:49:00,709 WETEXT INFO found existing fst: /opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/tn/en_tn_tagger.fst
INFO:wetext-en_normalizer:found existing fst: /opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/tn/en_tn_tagger.fst
2024-12-22 19:49:00,709 WETEXT INFO                     /opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/tn/en_tn_verbalizer.fst
INFO:wetext-en_normalizer:                    /opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/tn/en_tn_verbalizer.fst
2024-12-22 19:49:00,709 WETEXT INFO skip building fst for en_normalizer ...
INFO:wetext-en_normalizer:skip building fst for en_normalizer ...
INFO:__main__:Warming up CosyVoiceTTSHandler
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:22<00:00, 22.36s/it]
INFO:__main__:CosyVoiceTTSHandler:  warmed up! time: 22.423 s
Using cache found in /home/liweirong/.cache/torch/hub/snakers4_silero-vad_master
INFO:__main__:Receiver WebSocket server started at 0.0.0.0:39001
INFO:__main__:Sender WebSocket server started at 0.0.0.0:39002
INFO:__main__:Receiver WebSocket connected
^R
INFO:__main__:Receiver WebSocket connection OK closed
INFO:__main__:Receiver WebSocket connection end
INFO:__main__:Receiver WebSocket connected
INFO:__main__:VAD: end of speech detected: 448.0
INFO:__main__:inference ASR paraformer...
INFO:__main__:finish ASR paraformer inference
Sun Dec 22 19:50:49 2024        USER: 你好，
INFO:__main__:inference language model...
INFO:__main__:total input messages: [{'role': 'system', 'content': '\n# 角色\n你是一个说话简洁但风趣幽默的人，擅长与他人轻松愉快地交流。\n\n# 能力\n1. 风格适应：能根据用户的对话风格，灵活调整自己的说话方式和口语化程度，让对话更加自然亲切。\n2. 理解纠错：如果用户输入中有难以理解的字和词汇，可能是语音识别的误差，你会尝试给出几种可能的解释，并询问用户以确认，确定信息后再开始后续回答。如果没有，正常回答即可。\n3. 避免使用复杂的格式（比如 markdown 或强调符号**等），简单断句或分段即可，分点列举信息时不要超过4种，保持对话的流畅性。\n4. 分段回答：对于较长的知识性回答，不要直接长篇大论说很多，你需要先给出总体介绍，然后分成多个部分（不超过4个），每个部分只用简短的关键词指代，不要过度展开，用户如果追问细节，你再给出相应的详细介绍。\n\n# 例子\n用户输入1\n"我今天吃了个超级大的披萨，结果肚子疼得要命，是不是因为披萨泰拉了？"\n\n智能体输出1\n"哎呀，心疼你一秒！肚子疼得要命，你是不是在说披萨太辣了？还是你觉得可能是其他原因呢？比如，披萨是不是品质太差太垃圾了？我们一起想想办法，看看怎么样能帮你缓解一下？"\n\n用户输入2\n"你会和面吗？能给我讲讲做法吗？"\n\n智能体输出2\n和面的做法其实很简单，整体大概可以分为四步：准备材料、混合搅拌、揉面、醒面。你具体想了解哪一块呢？\n'}, {'role': 'user', 'content': '你好，'}]
INFO:__main__:Receiver WebSocket connection OK closed
INFO:__main__:Receiver WebSocket connection end
Exception in thread Thread-5 (run):
Traceback (most recent call last):
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpcore/_sync/http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/_base_client.py", line 866, in _request
    response = self._client.send(request, auth=self.custom_auth, stream=stream)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/liweirong/CleanS2S/backend/s2s_server_pipeline.py", line 194, in run
    for output in self.process(input):
  File "/home/liweirong/CleanS2S/backend/s2s_server_pipeline.py", line 1299, in process
    response = self.client.chat.completions.create(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/_base_client.py", line 1063, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/_base_client.py", line 842, in request
    return self._request(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/_base_client.py", line 898, in _request
    return self._retry_request(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/_base_client.py", line 933, in _retry_request
    return self._request(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/_base_client.py", line 898, in _request
    return self._retry_request(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/_base_client.py", line 933, in _retry_request
    return self._request(
  File "/opt/anaconda3/envs/liweirong-llm/lib/python3.10/site-packages/openai/_base_client.py", line 905, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
INFO:__main__:Receiver WebSocket connected
INFO:__main__:Receiver WebSocket connection OK closed
INFO:__main__:Receiver WebSocket connection end
INFO:__main__:Receiver WebSocket connected
INFO:__main__:Receiver WebSocket connection OK closed
INFO:__main__:Receiver WebSocket connection end

**Comment by PaParaZz1** [comment]
你可以尝试说完一句话后，按下 UI 上的静音按钮，避免其他环境声音错误触发打断对话的逻辑。

**Comment by AdamsLee** [comment]
> 你可以尝试说完一句话后，按下 UI 上的静音按钮，避免其他环境声音错误触发打断对话的逻辑。

具体打断对话的逻辑有哪些？应该不是环境声音的问题，周围环境很安静而且很多时候还没有说话就断了

**Comment by AdamsLee** [comment]
原来是NEXT_PUBLIC_FX_RECV_HOST端口号前后端配置不一致导致的（NEXT_PUBLIC_FX_SEND_HOST配置一致，NEXT_PUBLIC_FX_RECV_HOST不小心输入错误了）
